fixtures:
  repositories:
    'openstacklib':
      repo: 'git://github.com/enovance/puppet-openstacklib'
      ref: 'c374bed10f8af6000601fa407ebaef0833e1999c'
    'cinder':
      repo: 'git://github.com/enovance/puppet-cinder'
      ref: 'c9271e02d0d5a317ab390cfce9928601208f6073'
    'keystone':
      repo: 'git://github.com/enovance/puppet-keystone.git'
      ref: '45ac386600c0e79942834da8b69bf09a4809d7bd'
    'nova':
      repo: 'git://github.com/enovance/puppet-nova.git'
      ref: '3ffc5a263113232230b69e621e1b6167f2148390'
    'glance':
      repo: 'git://github.com/enovance/puppet-glance.git'
      ref: '78042d76c0854e16a55aaf05c03696d4d422e3c5'
    'horizon':
      repo: 'git://github.com/enovance/puppet-horizon'
      ref: '16b482ea21a70d8dd06ab4c98ac5a218399b0213'
    'swift':
      repo: 'git://github.com/enovance/puppet-swift'
      ref: '3ea00440361ff2452561d2cce808d938e39cce56'
    'neutron':
      repo: 'git://github.com/enovance/puppet-neutron'
      ref: 'cefbdc897d70fd1c1fc44e372f05336674efd940'
    'ceilometer':
      repo: 'git://github.com/enovance/puppet-ceilometer'
      ref: '957c2120d0ee0b9db08bfddcce996686ba61d97d'
    'heat':
      repo: 'git://github.com/enovance/puppet-heat'
      ref: '0e6d7eacecd70819384ac61ea3b9df38b90411b0'
    'trove':
      repo: 'git://github.com/enovance/puppet-trove'
      ref: '7d9db32423b25dcc227ea6a6d43c90c63fde0d58'
    'apt':
      repo: 'git://github.com/enovance/puppetlabs-apt.git'
      ref: '9b001af8775c7231ea2656b7eb43d6141b536f49'
    'apache':
      repo: 'git://github.com/enovance/puppetlabs-apache.git'
      ref: '58682faf74cdfc6c8d921d2be9322368c8a96cf9'
    'ceph':
      repo: 'git://github.com/enovance/puppet-ceph.git'
      ref: 'c50d91a6f790058a2b6975d6e1d6189f7c8b6687'
    'concat':
      repo: 'git://github.com/enovance/puppet-concat.git'
      ref: '04356974f72b90a1d0f57346a00e95a717924e43'
    'corosync':
      repo: 'git://github.com/enovance/puppetlabs-corosync.git'
      ref: '79b61302b07fef30b65a42f3b55229616018aacf'
    'datacat':
      repo: 'git://github.com/enovance/puppet-datacat.git'
      ref: '6a2017b31a8808de35b89d90b9e2b681ef9a0918'
    'firewall':
      repo: 'git://github.com/enovance/puppetlabs-firewall.git'
      ref: '6540b31b0ca0727094ddf44436274436d2853d6d'
    'pacemaker':
      repo: 'git://github.com/enovance/puppet-pacemaker.git'
      ref: '56bbb3580bb7fa62bf57c2ed7a30b938e42b8cc3'
    'elasticsearch':
      repo: 'git://github.com/enovance/puppet-elasticsearch.git'
      ref: '6d08442e8382f0f47388d4185122992c2d73cd9b'
    'gcc':
      repo: 'git://github.com/enovance/puppetlabs-gcc.git'
      ref: '272e6595a2f4824dafa71a2b751960659c05c35d'
    'git':
      repo: 'git://github.com/enovance/puppetlabs-git.git'
      ref: '0df1f62130a7752c728efb7555f2b07ca178ee5b'
    'fluentd':
      repo: 'git://github.com/enovance/puppet-fluentd.git'
      ref: 'd073a97002c569d8bfc38ac814ee33ed2cb13ca6'
    'logrotate':
      repo: 'git://github.com/enovance/puppet-logrotate.git'
      ref: 'f4d12356301fa2992f51dc7225037bb07556cb28'
    'haproxy':
      repo: 'git://github.com/enovance/puppetlabs-haproxy.git'
      ref: 'fc1166f28d411dfd4f59d4bfd6936595c014a11b'
    'keepalived':
      repo: 'git://github.com/enovance/puppet-module-keepalived.git'
      ref: 'eb345b6d3b25106cbe166028f2b8dd9974a10230'
    'kibana3':
      repo: 'git://github.com/enovance/kibana3.git'
      ref: '64fb5f898a0f062ebf188e53ba613b3b13e9d829'
    'mongodb':
      repo: 'git://github.com/enovance/puppetlabs-mongodb.git'
      ref: 'e3cc9a0ea895f6e01801e4620799c66c2337b7ed'
    'mysql':
      repo: 'git://github.com/enovance/puppetlabs-mysql.git'
      ref: '8b814d4d2cb5786a15e8e37fb3b7444d5d5f0d3f'
    'rabbitmq':
      repo: 'git://github.com/enovance/puppetlabs-rabbitmq'
      ref: '25420cb3c26c9a8432ab519d43c094d614d4fec4'
    'memcached':
      repo: 'git://github.com/enovance/puppet-memcached'
      ref: 'd009260de3c7623003318555ec5ca61217ea3ca1'
    'ntp':
      repo: 'git://github.com/enovance/puppetlabs-ntp.git'
      ref: 'eb02ba2937ce86fb609ae41499767244b78ec58d'
    'puppetdbquery':
      repo: 'git://github.com/enovance/puppet-puppetdbquery.git'
      ref: '89194917744f929bb600c31d7d6f822b529f5f03'
    'redis':
      repo: 'git://github.com/enovance/puppet-redis.git'
      ref: '1b2b2cea8c9acc08cfa01b42e47fad17f3c4d03d'
    'sysctl':
      repo: 'git://github.com/enovance/puppet-sysctl.git'
      ref: '4a463384e844f51b270428643a5b8beb3628e854'
    'uchiwa':
      repo: 'git://github.com/enovance/yelp-uchiwa.git'
      ref: '8eafd8167ff7d4f1cd696e4d098e3e1497c28279'
    'inifile':
      repo: 'git://github.com/enovance/puppetlabs-inifile'
      ref: 'ae23a4db97d2815ec305d0529912685f07746d3c'
    'vswitch':
      repo: 'git://github.com/enovance/puppet-vswitch'
      ref: '49dbaff15e8f017dbe365ebf08eb505472b695a1'
    'vcsrepo':
      repo: 'git://github.com/enovance/puppetlabs-vcsrepo.git'
      ref: '4592bfd59cd5d4795069798a14b483e16c98c1ff'
    'wget':
      repo: 'git://github.com/enovance/puppet-wget.git'
      ref: '1c3ea6f1c822a99b52defb87305ea5977cba4293'
    'stdlib':
      repo: 'git://github.com/enovance/puppetlabs-stdlib.git'
      ref: '8a9b2dfc0e463bec39c00c82c30e0a8a8b7867f3'
    'xinetd':
      repo: 'git://github.com/enovance/puppetlabs-xinetd.git'
      ref: '7557af0e418d1a587df04fe7d01322ff2473c32e'
    'rhnreg_ks':
      repo: 'git://github.com/enovance/puppet-rhnreg_ks.git'
      ref: '8fdc051992b44a09f39d3b510d7cd6db5ed5ff66'
    'dnsclient':
      repo: 'git://github.com/enovance/puppet-module-dnsclient.git'
      ref: '4158b30f4660623f98dcdbd1ce9b482556180b57'
    'boolean':
      repo: 'git://github.com/enovance/puppet-boolean.git'
      ref: '157011a4eaa27f1202a9d94335ee4876b26d377e'
    'kmod':
      repo: 'git://github.com/enovance/puppet-kmod.git'
      ref: 'accc40093e6f8ee9cc472e9eb6ba3bab4bad3a1f'
    'sensu':
      repo: 'git://github.com/enovance/sensu-puppet.git'
      ref: '4a16ebf3503bfc9ae6192ae3120cb29b9e5c8445'
    'ssh':
      repo: 'git://github.com/enovance/puppet-ssh.git'
      ref: '10675c0d80511a8cdd514af67b695887fa97ec40'
    'rpcbind':
      repo: 'git://github.com/enovance/puppet-module-rpcbind.git'
      ref: 'da943d26f09f9658159c1190e058bf1af88f465d'
    'rsyslog':
      repo: 'git://github.com/enovance/puppet-rsyslog.git'
      ref: '67c7c501b916ebd1a27a8a218d49602339526c4f'
    'rsync':
      repo: 'git://github.com/enovance/puppetlabs-rsync.git'
      ref: '7122983d89bf68bc4170415cc03212f6a8a4636e'
    'nfs':
      repo: 'git://github.com/enovance/puppet-module-nfs.git'
      ref: 'a806082ba5ed50fb6ed3c1a9791207e3a9189574'
    'common':
      repo: 'git://github.com/enovance/puppet-module-common.git'
      ref: '2d0606fce1078222dd483e731ec32807f5b4ca53'
    'types':
      repo: 'git://github.com/enovance/puppet-module-types.git'
      ref: '4c58ae8b6cdb1a9da3da9654a35375e274019dfb'
  symlinks:
    'cloud': '#{source_dir}'
