name    'eNovance-cloud'
version '1.3.0'
source  'https://github.com/enovance/puppet-openstack-cloud'
author  'eNovance'
license 'Apache License 2.0'
summary 'eNovance Openstack Module'
description 'Puppet module that pulls together all the individual components of Openstack, resulting is a complete and functional stack.'
project_page 'https://github.com/enovance/puppet-openstack-cloud'

dependency 'puppetlabs/glance', '>= 4.0.0'
dependency 'puppetlabs/horizon', '>= 4.0.0'
dependency 'puppetlabs/keystone', '>= 4.0.0'
dependency 'puppetlabs/nova', '>= 4.0.0'
dependency 'puppetlabs/cinder', '>= 4.0.0'
dependency 'puppetlabs/swift', '>= 4.0.0'
dependency 'puppetlabs/neutron', '>= 4.0.0'
dependency 'puppetlabs/ceilometer', '>= 4.0.0'
dependency 'puppetlabs/heat', '>= 4.0.0'
dependency 'eNovance/ceph', '>= 1.0.0'
